window.PRODUCTION_PLAN_DATA = {
  "sourceUrl": "https://docs.google.com/spreadsheets/d/1gR-a77vkgVxDu0jdSZ9RPhnGLC5OabIRHSRGBN0hZ18/edit?gid=659565457#gid=659565457",
  "generatedAt": "2026-07-01T16:20:16.974Z",
  "planYear": 2026,
  "planMonth": 7,
  "machines": [
    {
      "name": "#1 Arc ·Stack",
      "defaultCapacity": 850,
      "sheetOrder": 0
    },
    {
      "name": "#2 Arc ·Stack",
      "defaultCapacity": 850,
      "sheetOrder": 1
    },
    {
      "name": "#3 Cut Chamber",
      "defaultCapacity": 850,
      "sheetOrder": 2
    },
    {
      "name": "#4 GV2",
      "defaultCapacity": 850,
      "sheetOrder": 3
    },
    {
      "name": "#5 Arc Chute",
      "defaultCapacity": 850,
      "sheetOrder": 4
    },
    {
      "name": "#6 Arc Chute",
      "defaultCapacity": 850,
      "sheetOrder": 5
    },
    {
      "name": "#7 Arc Chute",
      "defaultCapacity": 850,
      "sheetOrder": 6
    },
    {
      "name": "#8 Arc Chute",
      "defaultCapacity": 850,
      "sheetOrder": 7
    },
    {
      "name": "1#-OCP-80T",
      "defaultCapacity": 1200,
      "sheetOrder": 8
    },
    {
      "name": "2# MHS-80T",
      "defaultCapacity": 1200,
      "sheetOrder": 9
    },
    {
      "name": "3# OCP-110T",
      "defaultCapacity": 1200,
      "sheetOrder": 10
    },
    {
      "name": "4# SN1-110T",
      "defaultCapacity": 1200,
      "sheetOrder": 11
    },
    {
      "name": "5# OCP-110T",
      "defaultCapacity": 1200,
      "sheetOrder": 12
    },
    {
      "name": "6# STD-150T",
      "defaultCapacity": 1200,
      "sheetOrder": 13
    },
    {
      "name": "7# GTX-300T",
      "defaultCapacity": 11701,
      "sheetOrder": 14
    },
    {
      "name": "8# GTX-500T",
      "defaultCapacity": 2644,
      "sheetOrder": 15
    },
    {
      "name": "9# OCP-110T",
      "defaultCapacity": 1019,
      "sheetOrder": 16
    },
    {
      "name": "10# OCP-260 T",
      "defaultCapacity": 762,
      "sheetOrder": 17
    },
    {
      "name": "11# 200T",
      "defaultCapacity": 1277,
      "sheetOrder": 18
    },
    {
      "name": "12# 200T",
      "defaultCapacity": 2228,
      "sheetOrder": 19
    },
    {
      "name": "#1 RW",
      "defaultCapacity": 1000,
      "sheetOrder": 20
    },
    {
      "name": "#2 RW",
      "defaultCapacity": 1000,
      "sheetOrder": 21
    },
    {
      "name": "#3 RW",
      "defaultCapacity": 1000,
      "sheetOrder": 22
    },
    {
      "name": "#8 Rubber Cap",
      "defaultCapacity": 1000,
      "sheetOrder": 23
    },
    {
      "name": "Bending #1",
      "defaultCapacity": 176,
      "sheetOrder": 24
    },
    {
      "name": "Bending #2",
      "defaultCapacity": 1320,
      "sheetOrder": 25
    },
    {
      "name": "Tapping",
      "defaultCapacity": 620,
      "sheetOrder": 26
    },
    {
      "name": "Riveting",
      "defaultCapacity": 650,
      "sheetOrder": 27
    },
    {
      "name": "CNC-C1",
      "defaultCapacity": 900,
      "sheetOrder": 28
    },
    {
      "name": "CNC-C2",
      "defaultCapacity": 900,
      "sheetOrder": 29
    },
    {
      "name": "CNC-C3",
      "defaultCapacity": 900,
      "sheetOrder": 30
    },
    {
      "name": "CNC-C4",
      "defaultCapacity": 900,
      "sheetOrder": 31
    },
    {
      "name": "CNC-C5",
      "defaultCapacity": 900,
      "sheetOrder": 32
    },
    {
      "name": "CNC-C6",
      "defaultCapacity": 900,
      "sheetOrder": 33
    },
    {
      "name": "RV1",
      "defaultCapacity": 650,
      "sheetOrder": 34
    },
    {
      "name": "RV2",
      "defaultCapacity": 650,
      "sheetOrder": 35
    },
    {
      "name": "SW1# spot",
      "defaultCapacity": 1400,
      "sheetOrder": 36
    },
    {
      "name": "SW#2 Spot",
      "defaultCapacity": 1400,
      "sheetOrder": 37
    },
    {
      "name": "SW#3 Spot",
      "defaultCapacity": 1400,
      "sheetOrder": 38
    },
    {
      "name": "SW4 NMS",
      "defaultCapacity": 4920,
      "sheetOrder": 39
    },
    {
      "name": "SW5 CU",
      "defaultCapacity": 1400,
      "sheetOrder": 40
    },
    {
      "name": "SW6 NLC",
      "defaultCapacity": 347,
      "sheetOrder": 41
    },
    {
      "name": "SW7 LC 600",
      "defaultCapacity": 1941,
      "sheetOrder": 42
    },
    {
      "name": "SW8 Door LC",
      "defaultCapacity": 1243,
      "sheetOrder": 43
    }
  ],
  "orders": [
    {
      "id": "base-0",
      "machine": "7# GTX-300T",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060768",
      "partName": "Metal Box 4-6WAY",
      "partNo": "BRU30887",
      "rmNo": "TH-ZJDB2026061799",
      "qty": 4000,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 4000,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 0
    },
    {
      "id": "base-0",
      "machine": "7# GTX-300T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Metal Box 4-6WAY",
      "partNo": "BRU30888",
      "rmNo": "",
      "qty": 2101,
      "unit": "pcs",
      "dueDate": "-",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 2101,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 0
    },
    {
      "id": "base-0",
      "machine": "7# GTX-300T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Resi Cover Bracket",
      "partNo": "NVE96548",
      "rmNo": "",
      "qty": 5600,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 5600,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 0
    },
    {
      "id": "base-3",
      "machine": "8# GTX-500T",
      "openDate": "2026-06-10",
      "orderNo": "TH-SCDD2026050476",
      "partName": "Gland plate",
      "partNo": "BRU53717",
      "rmNo": "",
      "qty": 5288,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 5288,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 3
    },
    {
      "id": "base-4",
      "machine": "9# OCP-110T",
      "openDate": "2026-06-10",
      "orderNo": "TH-SCDD2026030207",
      "partName": "Cover LUG100 450mm 18w",
      "partNo": "BRU53725",
      "rmNo": "",
      "qty": 163,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 163,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 4
    },
    {
      "id": "base-4",
      "machine": "9# OCP-110T",
      "openDate": "2026-06-10",
      "orderNo": "TH-SCDD2026030206",
      "partName": "Cover LUG100 450mm 12w",
      "partNo": "BRU53724",
      "rmNo": "",
      "qty": 145,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 145,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 4
    },
    {
      "id": "base-4",
      "machine": "9# OCP-110T",
      "openDate": "2026-05-13",
      "orderNo": "TH-SCDD2026050288",
      "partName": "LC600 COVER",
      "partNo": "75170154",
      "rmNo": "",
      "qty": 2000,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 2000,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 4
    },
    {
      "id": "base-4",
      "machine": "9# OCP-110T",
      "openDate": "2026-05-10",
      "orderNo": "TH-SCDD2026050317",
      "partName": "GLAND PLATE",
      "partNo": "75170148",
      "rmNo": "",
      "qty": 5447,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 5447,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 4
    },
    {
      "id": "base-4",
      "machine": "9# OCP-110T",
      "openDate": "2026-06-26",
      "orderNo": "TH-SCDD2026030680",
      "partName": "Cover LUG100 450mm 18w",
      "partNo": "BRU53725",
      "rmNo": "",
      "qty": 250,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 250,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 4
    },
    {
      "id": "base-4",
      "machine": "9# OCP-110T",
      "openDate": "2026-06-26",
      "orderNo": "TH-SCDD2026030679",
      "partName": "Cover LUG100 450mm 12w",
      "partNo": "BRU53724",
      "rmNo": "",
      "qty": 150,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 150,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 4
    },
    {
      "id": "base-4",
      "machine": "9# OCP-110T",
      "openDate": "2026-07-02",
      "orderNo": "2026070201",
      "partName": "10383086",
      "partNo": "10383086",
      "rmNo": "WIP",
      "qty": 6000,
      "unit": "pcs",
      "dueDate": "2026-07-10",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 6000,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 4
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060761",
      "partName": "Cover EZ250 750mm 30w",
      "partNo": "BRU53734",
      "rmNo": "TH-ZJDB2026061762",
      "qty": 120,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 120,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060760",
      "partName": "Cover EZ250 750mm 24w",
      "partNo": "BRU53732",
      "rmNo": "TH-ZJDB2026061790",
      "qty": 98,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 98,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060758",
      "partName": "Cover EZ100 750mm 36w",
      "partNo": "BRU53722",
      "rmNo": "TH-ZJDB2026061787",
      "qty": 200,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 200,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060766",
      "partName": "Metal Cover 4WAY",
      "partNo": "BRU30890",
      "rmNo": "TH-ZJDB2026061797",
      "qty": 2000,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 2000,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060767",
      "partName": "Metal Box 6WAY",
      "partNo": "BRU30891",
      "rmNo": "TH-ZJDB2026061798",
      "qty": 1000,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1000,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "BOX 2+6，6 WAY",
      "partNo": "NVE96520",
      "rmNo": "",
      "qty": 3132,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 3132,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "BOX 2+10，10 WAY",
      "partNo": "NVE96528",
      "rmNo": "",
      "qty": 2691,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 2691,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Door 900mm",
      "partNo": "BRU53749",
      "rmNo": "",
      "qty": 89,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 89,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Cover EZ100 600mm 24w",
      "partNo": "BRU53720",
      "rmNo": "",
      "qty": 93,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 93,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Cover EZ250 600mm 12w",
      "partNo": "BRU53730",
      "rmNo": "",
      "qty": 7,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 7,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Cover EZ250 600mm 18w",
      "partNo": "BRU53731",
      "rmNo": "",
      "qty": 12,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 12,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "U BOX 600mm",
      "partNo": "BRU53715",
      "rmNo": "",
      "qty": 1207,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1207,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "U BOX 900mm",
      "partNo": "BRU53771",
      "rmNo": "",
      "qty": 175,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 175,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "BOX 2+18，18 WAY",
      "partNo": "NVE96543",
      "rmNo": "",
      "qty": 88,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 88,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-03-10",
      "orderNo": "TH-SCDD2026030207",
      "partName": "Cover LUG100 450mm 18w",
      "partNo": "BRU53725",
      "rmNo": "",
      "qty": 163,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 163,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-03-10",
      "orderNo": "TH-SCDD2026030206",
      "partName": "Cover LUG100 450mm 12w",
      "partNo": "BRU53724",
      "rmNo": "",
      "qty": 145,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 145,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-05-05",
      "orderNo": "TH-SCDD2026050069",
      "partName": "LC600 BOX",
      "partNo": "75170145",
      "rmNo": "",
      "qty": 3600,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 3600,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-11",
      "orderNo": "TH-SCDD2026060223",
      "partName": "Extension BOX",
      "partNo": "NAT18070",
      "rmNo": "",
      "qty": 5,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 5,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-09",
      "orderNo": "TH-SCDD2026060150",
      "partName": "METAL BOX 8/10 WAY",
      "partNo": "NMS/BRU30888",
      "rmNo": "",
      "qty": 1000,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1000,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-10",
      "orderNo": "TH-SCDD2026060193",
      "partName": "Extension BOX",
      "partNo": "NAT18070",
      "rmNo": "",
      "qty": 5,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 5,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-13",
      "orderNo": "TH-SCDD2026060292",
      "partName": "Cover EZ250 600mm 12w",
      "partNo": "BRU53730",
      "rmNo": "",
      "qty": 37,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 37,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-13",
      "orderNo": "TH-SCDD2026060293",
      "partName": "Cover EZ250 600mm 18w",
      "partNo": "BRU53731",
      "rmNo": "",
      "qty": 40,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 40,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-13",
      "orderNo": "TH-SCDD2026060295",
      "partName": "Cover EZ250 750mm 24w",
      "partNo": "BRU53732",
      "rmNo": "",
      "qty": 68,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 68,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-19",
      "orderNo": "TH-SCDD2026060493",
      "partName": "Cover EZ250 750mm 30w",
      "partNo": "BRU53734",
      "rmNo": "",
      "qty": 67,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 67,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-24",
      "orderNo": "TH-SCDD2026060613",
      "partName": "BOX 2+10，10 WAY",
      "partNo": "NVE96528",
      "rmNo": "",
      "qty": 600,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 600,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-25",
      "orderNo": "TH-SCDD2026060638",
      "partName": "Door 450mm",
      "partNo": "BRU53743",
      "rmNo": "",
      "qty": 740,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 740,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-26",
      "orderNo": "TH-SCDD2026030680",
      "partName": "Cover LUG100 450mm 18w",
      "partNo": "BRU53725",
      "rmNo": "",
      "qty": 250,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 250,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-26",
      "orderNo": "TH-SCDD2026030679",
      "partName": "Cover LUG100 450mm 12w",
      "partNo": "BRU53724",
      "rmNo": "",
      "qty": 150,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 150,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-26",
      "orderNo": "TH-SCDD2026060683",
      "partName": "Cover EZ250 600mm 12w",
      "partNo": "BRU53730",
      "rmNo": "",
      "qty": 100,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 100,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-11",
      "machine": "10# OCP-260 T",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060743",
      "partName": "U BOX 900mm",
      "partNo": "BRU53771",
      "rmNo": "TH-ZJDB2026061763",
      "qty": 400,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 400,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 11
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060747",
      "partName": "Cover EZ100 600mm 24w",
      "partNo": "BRU53720",
      "rmNo": "",
      "qty": 1500,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1500,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060759",
      "partName": "Cover LUG100 750mm 42w",
      "partNo": "BRU53729",
      "rmNo": "",
      "qty": 23,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 23,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060754",
      "partName": "Cover EZ100 600mm 24w",
      "partNo": "BRU53720",
      "rmNo": "",
      "qty": 194,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 194,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Metal Box 4-6WAY",
      "partNo": "NMS/BRU30887",
      "rmNo": "",
      "qty": 4726,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 4726,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Cover LUG250 900mm 48w",
      "partNo": "BRU53746",
      "rmNo": "",
      "qty": 100,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 100,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Cover EZ250 900mm 36w",
      "partNo": "BRU53735",
      "rmNo": "",
      "qty": 127,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 127,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "METAL BOX 14WAY",
      "partNo": "NMS/BRU30889",
      "rmNo": "",
      "qty": 70,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 70,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Door 600mm",
      "partNo": "BRU53744",
      "rmNo": "",
      "qty": 1410,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1410,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Cover EZ100 600mm 18w",
      "partNo": "BRU53719",
      "rmNo": "",
      "qty": 596,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 596,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Cover EZ100 600mm 24w",
      "partNo": "BRU53720",
      "rmNo": "",
      "qty": 337,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 337,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Cover EZ100 600mm 30w",
      "partNo": "BRU53721",
      "rmNo": "",
      "qty": 360,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 360,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-10",
      "orderNo": "TH-SCDD2026050476",
      "partName": "Gland plate",
      "partNo": "BRU53717",
      "rmNo": "",
      "qty": 5288,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 5288,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-05-20",
      "orderNo": "TH-SCDD2026050632",
      "partName": "Metal Box 4-6WAY",
      "partNo": "NMS/BRU30887",
      "rmNo": "",
      "qty": 443,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 443,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-13",
      "orderNo": "TH-SCDD2026060292",
      "partName": "Cover LUG100 750mm 42w",
      "partNo": "BRU53729",
      "rmNo": "",
      "qty": 39,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 39,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-13",
      "orderNo": "TH-SCDD2026060298",
      "partName": "Cover EZ100 450mm 12w",
      "partNo": "BRU53718",
      "rmNo": "",
      "qty": 200,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 200,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-15",
      "orderNo": "TH-SCDD2026060323",
      "partName": "METAL COVER 4WAY",
      "partNo": "NMS/BRU30890",
      "rmNo": "",
      "qty": 35000,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 35000,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-15",
      "orderNo": "TH-SCDD2026060333",
      "partName": "Gland plate",
      "partNo": "BRU53717",
      "rmNo": "",
      "qty": 5387,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 5387,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-15",
      "orderNo": "TH-SCDD202606060334",
      "partName": "Metal Box 4-6WAY",
      "partNo": "NMS/BRU30887",
      "rmNo": "",
      "qty": 3000,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 3000,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-26",
      "orderNo": "TH-SCDD202606060681",
      "partName": "Cover EZ100 600mm 18w",
      "partNo": "BRU53719",
      "rmNo": "",
      "qty": 800,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 800,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "2026-06-26",
      "orderNo": "TH-SCDD202606060682",
      "partName": "Cover EZ100 600mm 30w",
      "partNo": "BRU53721",
      "rmNo": "",
      "qty": 400,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 400,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-41",
      "machine": "11# 200T",
      "openDate": "Cover EZ100 600mm 24w",
      "orderNo": "BRU53720",
      "partName": "1500",
      "partNo": "",
      "rmNo": "",
      "qty": 1020,
      "unit": "480",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1020,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 41
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Metal Box 8WAY",
      "partNo": "BRU30892",
      "rmNo": "",
      "qty": 1000,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1000,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060740",
      "partName": "U BOX 600mm",
      "partNo": "BRU53715",
      "rmNo": "",
      "qty": 800,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 800,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060770",
      "partName": "METAL BOX",
      "partNo": "DBF60-8-U",
      "rmNo": "",
      "qty": 100,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 100,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060769",
      "partName": "METAL BOX",
      "partNo": "DBF45-8-U",
      "rmNo": "",
      "qty": 300,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 300,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Resi Cover 4-Way",
      "partNo": "QGH11468",
      "rmNo": "",
      "qty": 1190,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1190,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Resi Cover 14-Way",
      "partNo": "NVE96533",
      "rmNo": "",
      "qty": 99,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 99,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Resi Cover 4+4-Way",
      "partNo": "QGH13944",
      "rmNo": "",
      "qty": 50,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 50,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Resi Cover 18Way",
      "partNo": "NVE96542",
      "rmNo": "",
      "qty": 120,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 120,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Resi Box Bracket",
      "partNo": "NVE96549",
      "rmNo": "",
      "qty": 6124,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 6124,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Resi Cover 6-Way",
      "partNo": "NVE96519",
      "rmNo": "",
      "qty": 836,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 836,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Resi Cover 10-Way",
      "partNo": "NVE96526",
      "rmNo": "",
      "qty": 577,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 577,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "U BOX 450mm",
      "partNo": "BRU53714",
      "rmNo": "",
      "qty": 85,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 85,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "U BOX 750mm",
      "partNo": "BRU53716",
      "rmNo": "",
      "qty": 13,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 13,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Door 450mm",
      "partNo": "BRU53743",
      "rmNo": "",
      "qty": 683,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 683,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-05-13",
      "orderNo": "TH-SCDD2026050301",
      "partName": "METAL COVER 6WAY",
      "partNo": "NMS/BRU30891",
      "rmNo": "",
      "qty": 2032,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 2032,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-05-18",
      "orderNo": "TH-SCDD2026050507",
      "partName": "LC600 FLAT DOOR",
      "partNo": "7517016200",
      "rmNo": "",
      "qty": 1243,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1243,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-05-13",
      "orderNo": "TH-SCDD2026060288",
      "partName": "LC600 COVER",
      "partNo": "75170154",
      "rmNo": "",
      "qty": 2000,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 2000,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-13",
      "orderNo": "TH-SCDD2026060280",
      "partName": "METAL BOX",
      "partNo": "DBF45-8-U",
      "rmNo": "",
      "qty": 200,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 200,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-13",
      "orderNo": "TH-SCDD2026060289",
      "partName": "Cover LUG100 600mm 30w",
      "partNo": "BRU53727",
      "rmNo": "",
      "qty": 100,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 100,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-25",
      "orderNo": "TH-SCDD2026060321",
      "partName": "Door 450mm",
      "partNo": "BRU53743",
      "rmNo": "",
      "qty": 376,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 376,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-15",
      "orderNo": "TH-SCDD2026060320",
      "partName": "U BOX 450mm",
      "partNo": "BRU53714",
      "rmNo": "",
      "qty": 400,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 400,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-25",
      "orderNo": "TH-SCDD2026060039",
      "partName": "Door 600mm",
      "partNo": "BRU53744",
      "rmNo": "",
      "qty": 564,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 564,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-25",
      "orderNo": "TH-SCDD2026060360",
      "partName": "U BOX 450mm",
      "partNo": "BRU53714",
      "rmNo": "",
      "qty": 564,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 564,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-62",
      "machine": "12# 200T",
      "openDate": "2026-06-25",
      "orderNo": "TH-SCDD2026060637",
      "partName": "U BOX 600mm",
      "partNo": "BRU53715",
      "rmNo": "",
      "qty": 600,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 600,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 62
    },
    {
      "id": "base-86",
      "machine": "Bending #1",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060765",
      "partName": "Cover EZ250 900 mm 48w",
      "partNo": "BRU53737",
      "rmNo": "",
      "qty": 137,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 137,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 86
    },
    {
      "id": "base-86",
      "machine": "Bending #1",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060763",
      "partName": "Cover EZ250 900 mm 42w",
      "partNo": "BRU53736",
      "rmNo": "",
      "qty": 109,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 109,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 86
    },
    {
      "id": "base-86",
      "machine": "Bending #1",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060755",
      "partName": "Cover EZ250 600mm 18w",
      "partNo": "BRU53731",
      "rmNo": "",
      "qty": 168,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 168,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 86
    },
    {
      "id": "base-86",
      "machine": "Bending #1",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060756",
      "partName": "Cover EZ100 750mm 36w",
      "partNo": "BRU53722",
      "rmNo": "",
      "qty": 200,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 200,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 86
    },
    {
      "id": "base-86",
      "machine": "Bending #1",
      "openDate": "2026-06-13",
      "orderNo": "TH-SCDD2026060289",
      "partName": "Cover LUG100 600mm 30w",
      "partNo": "BRU53727",
      "rmNo": "",
      "qty": 100,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 100,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 86
    },
    {
      "id": "base-86",
      "machine": "Bending #1",
      "openDate": "2026-06-13",
      "orderNo": "TH-SCDD2026060292",
      "partName": "Cover LUG100 750mm 42w",
      "partNo": "BRU53729",
      "rmNo": "",
      "qty": 39,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 39,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 86
    },
    {
      "id": "base-86",
      "machine": "Bending #1",
      "openDate": "2026-06-13",
      "orderNo": "TH-SCDD2026060292",
      "partName": "Cover EZ250 600mm 12w",
      "partNo": "BRU53730",
      "rmNo": "",
      "qty": 37,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 37,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 86
    },
    {
      "id": "base-86",
      "machine": "Bending #1",
      "openDate": "2026-06-13",
      "orderNo": "TH-SCDD2026060293",
      "partName": "Cover EZ250 600mm 18w",
      "partNo": "BRU53731",
      "rmNo": "",
      "qty": 40,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 40,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 86
    },
    {
      "id": "base-86",
      "machine": "Bending #1",
      "openDate": "2026-06-13",
      "orderNo": "TH-SCDD2026060298",
      "partName": "Cover EZ100 450mm 12w",
      "partNo": "BRU53718",
      "rmNo": "",
      "qty": 200,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 200,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 86
    },
    {
      "id": "base-86",
      "machine": "Bending #1",
      "openDate": "2026-06-13",
      "orderNo": "TH-SCDD2026060295",
      "partName": "Cover EZ250 750mm 24w",
      "partNo": "BRU53732",
      "rmNo": "",
      "qty": 68,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 68,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 86
    },
    {
      "id": "base-86",
      "machine": "Bending #1",
      "openDate": "2026-06-26",
      "orderNo": "TH-SCDD202606060681",
      "partName": "Cover EZ100 600mm 18w",
      "partNo": "BRU53719",
      "rmNo": "",
      "qty": 800,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 800,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 86
    },
    {
      "id": "base-86",
      "machine": "Bending #1",
      "openDate": "2026-06-10",
      "orderNo": "TH-SCDD2026030206",
      "partName": "Cover LUG100 450mm 12w",
      "partNo": "BRU53724",
      "rmNo": "",
      "qty": 145,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 145,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 86
    },
    {
      "id": "base-86",
      "machine": "Bending #1",
      "openDate": "2026-06-26",
      "orderNo": "TH-SCDD2026030679",
      "partName": "Cover LUG100 450mm 12w",
      "partNo": "BRU53724",
      "rmNo": "",
      "qty": 150,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 150,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 86
    },
    {
      "id": "base-86",
      "machine": "Bending #1",
      "openDate": "2026-06-26",
      "orderNo": "TH-SCDD2026060683",
      "partName": "Cover EZ250 600mm 12w",
      "partNo": "BRU53730",
      "rmNo": "",
      "qty": 100,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 100,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 86
    },
    {
      "id": "base-86",
      "machine": "Bending #1",
      "openDate": "Cover EZ100 600mm 24w",
      "orderNo": "BRU53720",
      "partName": "1500",
      "partNo": "",
      "rmNo": "",
      "qty": 1020,
      "unit": "480",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1020,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 86
    },
    {
      "id": "base-101",
      "machine": "Bending #2",
      "openDate": "2026-06-10",
      "orderNo": "-",
      "partName": "LC 600 Curve door",
      "partNo": "7517016600",
      "rmNo": "",
      "qty": 100,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 100,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 101
    },
    {
      "id": "base-101",
      "machine": "Bending #2",
      "openDate": "2026-05-05",
      "orderNo": "TH-SCDD2026050069",
      "partName": "LC600 BOX",
      "partNo": "7517014500",
      "rmNo": "",
      "qty": 3600,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 3600,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 101
    },
    {
      "id": "base-101",
      "machine": "Bending #2",
      "openDate": "2026-05-18",
      "orderNo": "TH-SCDD2026050507",
      "partName": "LC600 FLAT DOOR",
      "partNo": "7517016200",
      "rmNo": "",
      "qty": 1243,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1243,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 101
    },
    {
      "id": "base-101",
      "machine": "Bending #2",
      "openDate": "2026-05-13",
      "orderNo": "TH-SCDD2026060288",
      "partName": "LC600 COVER",
      "partNo": "75170154",
      "rmNo": "",
      "qty": 2000,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 2000,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 101
    },
    {
      "id": "base-101",
      "machine": "Bending #2",
      "openDate": "2026-06-19",
      "orderNo": "TH-SCDD2026060493",
      "partName": "Cover EZ250 750mm 30w",
      "partNo": "BRU53734",
      "rmNo": "",
      "qty": 67,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 67,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 101
    },
    {
      "id": "base-101",
      "machine": "Bending #2",
      "openDate": "2026-06-26",
      "orderNo": "TH-SCDD2026030680",
      "partName": "Cover LUG100 450mm 18w",
      "partNo": "BRU53725",
      "rmNo": "",
      "qty": 250,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 250,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 101
    },
    {
      "id": "base-101",
      "machine": "Bending #2",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Cover EZ100 600mm 30w",
      "partNo": "BRU53721",
      "rmNo": "",
      "qty": 360,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 360,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 101
    },
    {
      "id": "base-101",
      "machine": "Bending #2",
      "openDate": "2026-06-26",
      "orderNo": "TH-SCDD202606060682",
      "partName": "Cover EZ100 600mm 30w",
      "partNo": "BRU53721",
      "rmNo": "",
      "qty": 400,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 400,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 101
    },
    {
      "id": "base-101",
      "machine": "Bending #2",
      "openDate": "Cover EZ100 600mm 24w",
      "orderNo": "BRU53720",
      "partName": "1500",
      "partNo": "",
      "rmNo": "",
      "qty": 1020,
      "unit": "480",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1020,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 101
    },
    {
      "id": "base-110",
      "machine": "Tapping",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060761",
      "partName": "U BOX 900mm",
      "partNo": "BRU53771",
      "rmNo": "",
      "qty": 400,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 400,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 110
    },
    {
      "id": "base-110",
      "machine": "Tapping",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060741",
      "partName": "U BOX 750mm",
      "partNo": "BRU53716",
      "rmNo": "",
      "qty": 600,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 600,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 110
    },
    {
      "id": "base-110",
      "machine": "Tapping",
      "openDate": "2026-05-05",
      "orderNo": "TH-SCDD2026050069",
      "partName": "LC600 BOX",
      "partNo": "7517014500",
      "rmNo": "",
      "qty": 3600,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 3600,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 110
    },
    {
      "id": "base-110",
      "machine": "Tapping",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "U BOX 450mm",
      "partNo": "BRU53714",
      "rmNo": "",
      "qty": 85,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 85,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 110
    },
    {
      "id": "base-110",
      "machine": "Tapping",
      "openDate": "2026-06-15",
      "orderNo": "TH-SCDD2026060320",
      "partName": "U BOX 450mm",
      "partNo": "BRU53714",
      "rmNo": "",
      "qty": 400,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 400,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 110
    },
    {
      "id": "base-110",
      "machine": "Tapping",
      "openDate": "2026-06-25",
      "orderNo": "TH-SCDD2026060360",
      "partName": "U BOX 450mm",
      "partNo": "BRU53714",
      "rmNo": "",
      "qty": 564,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 564,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 110
    },
    {
      "id": "base-110",
      "machine": "Tapping",
      "openDate": "2026-06-25",
      "orderNo": "TH-SCDD2026060637",
      "partName": "U BOX 600mm",
      "partNo": "BRU53715",
      "rmNo": "",
      "qty": 600,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 600,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 110
    },
    {
      "id": "base-110",
      "machine": "Tapping",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "U BOX 900mm",
      "partNo": "BRU53771",
      "rmNo": "",
      "qty": 175,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 175,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 110
    },
    {
      "id": "base-110",
      "machine": "Tapping",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060743",
      "partName": "U BOX 900mm",
      "partNo": "BRU53771",
      "rmNo": "",
      "qty": 400,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 400,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 110
    },
    {
      "id": "base-119",
      "machine": "SW4 NMS",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "Metal Box 4-6WAY",
      "partNo": "NMS/BRU30887",
      "rmNo": "",
      "qty": 4726,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 4726,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 119
    },
    {
      "id": "base-119",
      "machine": "SW4 NMS",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "METAL BOX 14WAY",
      "partNo": "NMS/BRU30889",
      "rmNo": "",
      "qty": 70,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 70,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 119
    },
    {
      "id": "base-119",
      "machine": "SW4 NMS",
      "openDate": "2026-05-20",
      "orderNo": "TH-SCDD2026050632",
      "partName": "Metal Box 4-6WAY",
      "partNo": "NMS/BRU30887",
      "rmNo": "",
      "qty": 443,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 443,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 119
    },
    {
      "id": "base-119",
      "machine": "SW4 NMS",
      "openDate": "2026-06-09",
      "orderNo": "TH-SCDD2026060150",
      "partName": "METAL BOX 8/10 WAY",
      "partNo": "NMS/BRU30888",
      "rmNo": "",
      "qty": 1000,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1000,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 119
    },
    {
      "id": "base-119",
      "machine": "SW4 NMS",
      "openDate": "2026-06-15",
      "orderNo": "TH-SCDD202606060334",
      "partName": "Metal Box 4-6WAY",
      "partNo": "NMS/BRU30887",
      "rmNo": "",
      "qty": 3000,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 3000,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 119
    },
    {
      "id": "base-119",
      "machine": "SW4 NMS",
      "openDate": "2026-06-24",
      "orderNo": "TH-SCDD2026060613",
      "partName": "BOX 2+10，10 WAY",
      "partNo": "NVE96528",
      "rmNo": "",
      "qty": 600,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 600,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 119
    },
    {
      "id": "base-119",
      "machine": "SW4 NMS",
      "openDate": "Cover EZ100 600mm 24w",
      "orderNo": "BRU53720",
      "partName": "1500",
      "partNo": "",
      "rmNo": "",
      "qty": 1020,
      "unit": "480",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1020,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 119
    },
    {
      "id": "base-126",
      "machine": "SW6 NLC",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060738",
      "partName": "Door 900mm",
      "partNo": "BRU53749",
      "rmNo": "",
      "qty": 200,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 200,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 126
    },
    {
      "id": "base-126",
      "machine": "SW6 NLC",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060743",
      "partName": "Door 750mm",
      "partNo": "BRU53747",
      "rmNo": "",
      "qty": 200,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 200,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 126
    },
    {
      "id": "base-126",
      "machine": "SW6 NLC",
      "openDate": "2026-06-25",
      "orderNo": "TH-SCDD2026060321",
      "partName": "Door 450mm",
      "partNo": "BRU53743",
      "rmNo": "",
      "qty": 376,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 376,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 126
    },
    {
      "id": "base-126",
      "machine": "SW6 NLC",
      "openDate": "2026-06-25",
      "orderNo": "TH-SCDD20260600390",
      "partName": "Door 600mm",
      "partNo": "BRU53744",
      "rmNo": "",
      "qty": 564,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 564,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 126
    },
    {
      "id": "base-126",
      "machine": "SW6 NLC",
      "openDate": "2026-06-25",
      "orderNo": "TH-SCDD2026060638",
      "partName": "Door 450mm",
      "partNo": "BRU53743",
      "rmNo": "",
      "qty": 740,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 740,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 126
    },
    {
      "id": "base-126",
      "machine": "SW6 NLC",
      "openDate": "Cover EZ100 600mm 24w",
      "orderNo": "BRU53720",
      "partName": "1500",
      "partNo": "",
      "rmNo": "",
      "qty": 1020,
      "unit": "480",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1020,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 126
    },
    {
      "id": "base-132",
      "machine": "SW7 LC 600",
      "openDate": "2026-05-05",
      "orderNo": "TH-SCDD2026050069",
      "partName": "LC600 BOX",
      "partNo": "7517014500",
      "rmNo": "",
      "qty": 3600,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 3600,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 132
    },
    {
      "id": "base-132",
      "machine": "SW7 LC 600",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "U BOX 450mm",
      "partNo": "BRU53714",
      "rmNo": "",
      "qty": 85,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 85,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 132
    },
    {
      "id": "base-132",
      "machine": "SW7 LC 600",
      "openDate": "2026-06-15",
      "orderNo": "TH-SCDD2026060320",
      "partName": "U BOX 450mm",
      "partNo": "BRU53714",
      "rmNo": "",
      "qty": 400,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 400,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 132
    },
    {
      "id": "base-132",
      "machine": "SW7 LC 600",
      "openDate": "2026-06-25",
      "orderNo": "TH-SCDD2026060360",
      "partName": "U BOX 450mm",
      "partNo": "BRU53714",
      "rmNo": "",
      "qty": 564,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 564,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 132
    },
    {
      "id": "base-132",
      "machine": "SW7 LC 600",
      "openDate": "2026-06-25",
      "orderNo": "TH-SCDD2026060637",
      "partName": "U BOX 600mm",
      "partNo": "BRU53715",
      "rmNo": "",
      "qty": 600,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 600,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 132
    },
    {
      "id": "base-132",
      "machine": "SW7 LC 600",
      "openDate": "2026-06-10",
      "orderNo": "WIP",
      "partName": "U BOX 900mm",
      "partNo": "BRU53771",
      "rmNo": "",
      "qty": 175,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 175,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 132
    },
    {
      "id": "base-132",
      "machine": "SW7 LC 600",
      "openDate": "2026-06-29",
      "orderNo": "TH-SCDD2026060743",
      "partName": "U BOX 900mm",
      "partNo": "BRU53771",
      "rmNo": "",
      "qty": 400,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 400,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 132
    },
    {
      "id": "base-132",
      "machine": "SW7 LC 600",
      "openDate": "Cover EZ100 600mm 24w",
      "orderNo": "BRU53720",
      "partName": "1500",
      "partNo": "",
      "rmNo": "",
      "qty": 1020,
      "unit": "480",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1020,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 132
    },
    {
      "id": "base-140",
      "machine": "SW8 Door LC",
      "openDate": "2026-06-10",
      "orderNo": "-",
      "partName": "LC 600 Curve door",
      "partNo": "7517016600",
      "rmNo": "",
      "qty": 100,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 100,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 140
    },
    {
      "id": "base-140",
      "machine": "SW8 Door LC",
      "openDate": "2026-05-18",
      "orderNo": "TH-SCDD2026050507",
      "partName": "LC600 FLAT DOOR",
      "partNo": "7517016200",
      "rmNo": "",
      "qty": 1243,
      "unit": "pcs",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1243,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 140
    },
    {
      "id": "base-140",
      "machine": "SW8 Door LC",
      "openDate": "Cover EZ100 600mm 24w",
      "orderNo": "BRU53720",
      "partName": "1500",
      "partNo": "",
      "rmNo": "",
      "qty": 1020,
      "unit": "480",
      "dueDate": "",
      "shift": "",
      "plannedStart": "",
      "plannedFinish": "",
      "produced": 0,
      "readyForPainting": 0,
      "remaining": 1020,
      "ngRework": 0,
      "productionStatus": "",
      "progress": "",
      "stock": "",
      "sourceIndex": 140
    }
  ]
};
